import { cssComment, cssString } from "./shared.js";
import {
  SYSTEM_ORDER,
  SYSTEM_STYLE_IMPORTS,
  THEME_MODE_ATTRIBUTE,
  normalizeTrebiredFrontendConfig,
} from "./normalize.js";
import { flattenThemeTokens } from "./theme.js";
import type {
  NormalizedTrebiredFrontendConfig,
  NormalizedTrebiredFrontendThemeMode,
  TrebiredFrontendConfig,
  TrebiredFrontendThemeTokens,
} from "./types.js";

function tokenDeclarations(prefix: string, tokens: TrebiredFrontendThemeTokens): string[] {
  return flattenThemeTokens(tokens).map(([key, value]) => `  --${prefix}-${key}: ${String(value)};`);
}

function rootDeclarations(config: NormalizedTrebiredFrontendConfig): string[] {
  const { modes, defaultMode } = config.theme;
  return [
    `  --${config.prefix}-config-prefix: ${cssString(config.prefix)};`,
    `  --${config.prefix}-icon-endpoint: ${cssString(config.icons.endpoint)};`,
    ...(modes.length ? [`  --${config.prefix}-theme-modes: ${cssString(modes.map((mode) => mode.key).join(" "))};`] : []),
    ...(defaultMode ? [`  --${config.prefix}-theme-default: ${cssString(defaultMode)};`] : []),
    ...tokenDeclarations(config.prefix, config.theme.tokens),
  ];
}

function modeDeclarations(
  config: NormalizedTrebiredFrontendConfig,
  mode: NormalizedTrebiredFrontendThemeMode,
): string[] {
  return [
    `  color-scheme: ${mode.scheme};`,
    ...tokenDeclarations(config.prefix, mode.tokens),
  ];
}

function renderBlock(selector: string, declarations: string[], indent = ""): string[] {
  if (!declarations.length) return [];
  return [
    `${indent}${selector} {`,
    ...declarations.map((line) => `${indent}${line}`),
    `${indent}}`,
  ];
}

function renderModeBlocks(config: NormalizedTrebiredFrontendConfig): string[] {
  return config.theme.modes.flatMap((mode) => [
    "",
    `/* theme mode: ${cssComment(mode.key)} */`,
    ...renderBlock(`[${THEME_MODE_ATTRIBUTE}="${mode.key}"]`, modeDeclarations(config, mode)),
  ]);
}

function renderSystemPreferenceBlock(
  config: NormalizedTrebiredFrontendConfig,
  scheme: "dark" | "light",
): string[] {
  const key = scheme === "dark" ? config.theme.dark : config.theme.light;
  const mode = config.theme.modes.find((item) => item.key === key);
  if (!mode) return [];
  return [
    "",
    `@media (prefers-color-scheme: ${scheme}) {`,
    ...renderBlock(`:root:not([${THEME_MODE_ATTRIBUTE}])`, modeDeclarations(config, mode), "  "),
    "}",
  ];
}

function renderThemeCss(config: NormalizedTrebiredFrontendConfig): string[] {
  if (!config.theme.cssVariables) return [];
  return [
    "",
    ...renderBlock(":root", rootDeclarations(config)),
    ...renderModeBlocks(config),
    ...renderSystemPreferenceBlock(config, "dark"),
    ...renderSystemPreferenceBlock(config, "light"),
  ];
}

function renderSystemImports(config: NormalizedTrebiredFrontendConfig): string[] {
  const lines: string[] = [];
  for (const system of SYSTEM_ORDER) {
    const importPath = SYSTEM_STYLE_IMPORTS[system];
    if (importPath && config.systems[system]) lines.push(`@use ${cssString(importPath)} as *;`);
  }
  return lines;
}

function generateTrebiredFrontendScss(
  configInput: TrebiredFrontendConfig | NormalizedTrebiredFrontendConfig,
): string {
  const config = normalizeTrebiredFrontendConfig(configInput);
  const lines = [
    "/* Generated by @trebired/frontend. Do not edit directly. */",
    `/* prefix: ${cssComment(config.prefix)} */`,
    '@use "@trebired/frontend/styles/tokens" as *;',
    '@use "@trebired/frontend/styles/utils" as *;',
    ...renderSystemImports(config),
    ...renderThemeCss(config),
  ];
  return `${lines.join("\n")}\n`;
}

export { generateTrebiredFrontendScss };
